<?php if ($isAdmin || $isDirector): ?>
<!-- ─── RECENT REPORTS ACTIVITY CARD ─── -->
<div id="recentReports" class="report-card rounded-3xl p-5 sm:p-7 mb-8">
    <div class="card-shape card-shape-1"></div>
    <div class="dot-pattern absolute inset-0"></div>

    <div class="relative z-10">
        <div class="flex items-center justify-between mb-4">
            <div>
                <h3 class="text-base font-semibold text-[#176B87] flex items-center gap-2">
                    <i class="fa-solid fa-clock-rotate-left text-[#86B6F6] text-sm"></i>
                    Recent Report Logs
                </h3>
                <p class="text-xs text-slate-400">Audit trail of users who generated and exported reports</p>
            </div>
        </div>
        <div class="table-wrap overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="text-left text-xs font-semibold text-[#176B87] uppercase tracking-wider border-b border-[#B4D4FF]/30">
                    <tr>
                        <th class="pb-2 pr-4">Report Name</th>
                        <th class="pb-2 pr-4">Format / Type</th>
                        <th class="pb-2 pr-4">Generated By</th>
                        <th class="pb-2 pr-4">Date &amp; Time</th>
                        <th class="pb-2">Status</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-[#B4D4FF]/20" id="recentReportsBody"></tbody>
            </table>
        </div>
        <div class="mt-4 flex items-center justify-between" id="recentReportsPagination">
            <span class="text-xs text-slate-500" id="recentReportsCount">Showing 0 to 0 of 0 entries</span>
            <div class="flex gap-2">
                <button onclick="prevRecentPage()" class="px-3 py-1.5 text-xs font-medium bg-[#B4D4FF]/20 text-[#176B87] rounded-lg hover:bg-[#B4D4FF]/40 transition disabled:opacity-50" id="btnPrevRecent">Prev</button>
                <button onclick="nextRecentPage()" class="px-3 py-1.5 text-xs font-medium bg-[#B4D4FF]/20 text-[#176B87] rounded-lg hover:bg-[#B4D4FF]/40 transition disabled:opacity-50" id="btnNextRecent">Next</button>
            </div>
        </div>
    </div>
</div>
<?php endif; ?>
